// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjxmvpmzdmlpvfsbbmzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qeG12cG16ZG1scHZmc2JibXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzMwODcsImV4cCI6MjA1NTA0OTA4N30.E3f4cidBFjVFjsyNoDQrE51LceZx7jNWpzg2QElvzkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);